{% set name = "msgraph-sdk" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/msgraph_sdk-{{ version }}.tar.gz
  sha256: 715907272c240e579d7669a690504488e25ae15fec904e2918c49ca328dc4a14

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=65.5.0
    - wheel
    - pip
  run:
    - python >=3.8
    - azure-identity >=1.12.0
    - microsoft-kiota-abstractions >=1.0.0,<2.0.0
    - microsoft-kiota-authentication-azure >=1.0.0,<2.0.0
    - microsoft-kiota-serialization-json >=1.0.0,<2.0.0
    - microsoft-kiota-serialization-text >=1.0.0,<2.0.0
    - microsoft-kiota-serialization-form >=0.1.0
    - microsoft-kiota-serialization-multipart >=0.1.0
    - microsoft-kiota-http >=1.0.0,<2.0.0
    - msgraph-core >=1.0.0

test:
  imports:
    - msgraph_sdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoftgraph/msgraph-sdk-python
  summary: The Microsoft Graph Python SDK
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/microsoftgraph/msgraph-sdk-python
  doc_url: https://github.com/microsoftgraph/msgraph-sdk-python#readme
extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/48409
    reason: Dependenccy for msgraph-sdk
    recipe-maintainers:
      - ianaobi
      - bkreider
