{% set name = "msgraph-sdk" %}
{% set version = "1.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/msgraph_sdk-{{ version }}.tar.gz
  sha256: 577e41942b0f794b8cf2f54db030bc039a750a81b515dcd0ba1d66fd961fa7bf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=65.5.0
    - wheel
    - pip
    - flit-core
  run:
    - python >=3.8
    - azure-identity
    - microsoft-kiota-abstractions 
    - microsoft-kiota-authentication-azure
    - microsoft-kiota-serialization-json 
    - microsoft-kiota-serialization-text
    - microsoft-kiota-serialization-form
    - microsoft-kiota-serialization-multipart 
    - microsoft-kiota-http 
    - msgraph-core 
    - flit-core

test:
  imports:
    - msgraph
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoftgraph/msgraph-sdk-python
  summary: The Microsoft Graph Python SDK
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/microsoftgraph/msgraph-sdk-python
  doc_url: https://github.com/microsoftgraph/msgraph-sdk-python#readme
extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/64252
    reason: Dependenccy for msgraph-sdk
    recipe-maintainers:
      - ianaobi
      - bkreider
